# Traefik 静态配置
# Nova Proxy 负载均衡和路由配置

# 全局配置
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# 入口点配置
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  
  websecure:
    address: ":443"
    http:
      tls:
        options: default
  
  traefik:
    address: ":8080"
  
  metrics:
    address: ":8082"

# 提供者配置
providers:
  # Docker 提供者
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: nova-network
    watch: true
  
  # 文件提供者（动态配置）
  file:
    directory: /etc/traefik/dynamic
    watch: true

# API 和仪表板
api:
  dashboard: true
  debug: true
  insecure: true  # 仅开发环境，生产环境应设为 false

# 日志配置
log:
  level: INFO
  format: json
  filePath: "/var/log/traefik/traefik.log"

# 访问日志
accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json
  bufferingSize: 100
  filters:
    statusCodes:
      - "400-499"
      - "500-599"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

# 指标配置
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

# 追踪配置
# tracing:
#   jaeger:
#     samplingServerURL: http://jaeger:14268/api/sampling
#     samplingType: const
#     samplingParam: 1.0
#     localAgentHostPort: jaeger:6831
#     gen128Bit: true
#     propagation: jaeger
#     traceContextHeaderName: uber-trace-id

# 证书解析器（Let's Encrypt）
certificatesResolvers:
  letsencrypt:
    acme:
      tlsChallenge: {}
      email: admin@nova-proxy.local
      storage: /letsencrypt/acme.json
      # 使用 Let's Encrypt 暂存环境进行测试
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory

# 健康检查
ping:
  entryPoint: traefik

# 集群配置（如果需要）
# cluster:
#   store: consul
#   prefix: traefik

# 实验性功能
# experimental:
#   plugins:
#     # 可以在这里添加插件配置
#   localPlugins:
#     # 本地插件配置

# 服务发现
servicesThrottleDuration: 2s