# Nova Proxy Kubernetes ConfigMap 配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-proxy-config
  labels:
    app: nova-proxy
    component: config
data:
  # 日志配置
  log-level: "info"
  log-format: "json"
  log-output: "stdout"
  
  # 服务器配置
  server-host: "0.0.0.0"
  quic-port: "8080"
  https-port: "8443"
  health-port: "8081"
  metrics-port: "9090"
  
  # QUIC 配置
  quic-idle-timeout: "30s"
  quic-handshake-timeout: "10s"
  quic-max-streams: "100"
  quic-max-stream-data: "1048576"
  quic-max-connection-data: "10485760"
  
  # 性能配置
  max-connections: "10000"
  connection-timeout: "30s"
  read-timeout: "10s"
  write-timeout: "10s"
  
  # 监控配置
  metrics-enabled: "true"
  health-check-enabled: "true"
  tracing-enabled: "true"
  
  # 安全配置
  tls-min-version: "1.3"
  cipher-suites: "TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256"
  
  # 主配置文件
  config.yaml: |
    # Nova Proxy 主配置文件
    server:
      host: "0.0.0.0"
      quic_port: 8080
      https_port: 8443
      health_port: 8081
      metrics_port: 9090
      
    logging:
      level: "info"
      format: "json"
      output: "stdout"
      rotation:
        enabled: false  # 在容器环境中禁用文件轮转
      sanitization:
        enabled: true
        patterns:
          - "password"
          - "token"
          - "secret"
          - "key"
    
    quic:
      idle_timeout: "30s"
      handshake_timeout: "10s"
      max_streams: 100
      max_stream_data: 1048576
      max_connection_data: 10485760
      keep_alive: true
      
    performance:
      max_connections: 10000
      connection_timeout: "30s"
      read_timeout: "10s"
      write_timeout: "10s"
      buffer_size: 65536
      
    security:
      tls:
        min_version: "1.3"
        cipher_suites:
          - "TLS_AES_256_GCM_SHA384"
          - "TLS_CHACHA20_POLY1305_SHA256"
          - "TLS_AES_128_GCM_SHA256"
        cert_file: "/app/certs/tls.crt"
        key_file: "/app/certs/tls.key"
      
    monitoring:
      metrics:
        enabled: true
        path: "/metrics"
        port: 9090
      health:
        enabled: true
        path: "/health"
        ready_path: "/ready"
        port: 8081
      tracing:
        enabled: true
        jaeger_endpoint: "http://jaeger-collector:14268/api/traces"
        
    profiles:
      config_dir: "/app/profiles"
      reload_interval: "5m"
      
---
# Nova Proxy 调度器配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-proxy-profiles
  labels:
    app: nova-proxy
    component: profiles
data:
  # 默认调度器配置
  default.yaml: |
    # 默认 MPQUIC 调度器配置
    scheduler:
      name: "round_robin"
      parameters:
        weight_factor: 1.0
        latency_threshold: "100ms"
        bandwidth_threshold: "1Mbps"
        
    paths:
      - name: "primary"
        priority: 1
        weight: 0.7
        max_bandwidth: "100Mbps"
        latency_target: "50ms"
        
      - name: "secondary"
        priority: 2
        weight: 0.3
        max_bandwidth: "50Mbps"
        latency_target: "100ms"
        
  # 低延迟调度器配置
  low_latency.yaml: |
    # 低延迟优化调度器配置
    scheduler:
      name: "lowest_latency"
      parameters:
        latency_weight: 0.8
        bandwidth_weight: 0.2
        measurement_window: "1s"
        
    paths:
      - name: "fast_path"
        priority: 1
        weight: 1.0
        max_bandwidth: "1Gbps"
        latency_target: "10ms"
        
  # 高吞吐调度器配置
  high_throughput.yaml: |
    # 高吞吐优化调度器配置
    scheduler:
      name: "highest_bandwidth"
      parameters:
        bandwidth_weight: 0.9
        latency_weight: 0.1
        congestion_threshold: 0.8
        
    paths:
      - name: "bulk_path"
        priority: 1
        weight: 1.0
        max_bandwidth: "10Gbps"
        latency_target: "200ms"