{{/*
Nova Proxy Secret 模板
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nova-proxy.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nova-proxy.labels" . | nindent 4 }}
    {{- with .Values.extra.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.secret.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: {{ .Values.secret.type | default "Opaque" }}
data:
  {{- if .Values.secret.data }}
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  
  # TLS 证书和密钥
  {{- if .Values.tls.cert }}
  tls.crt: {{ .Values.tls.cert | b64enc }}
  {{- end }}
  {{- if .Values.tls.key }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- end }}
  {{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca | b64enc }}
  {{- end }}
  
  # 数据库连接信息
  {{- if .Values.database.enabled }}
  {{- if .Values.database.host }}
  DB_HOST: {{ .Values.database.host | b64enc }}
  {{- end }}
  {{- if .Values.database.port }}
  DB_PORT: {{ .Values.database.port | toString | b64enc }}
  {{- end }}
  {{- if .Values.database.name }}
  DB_NAME: {{ .Values.database.name | b64enc }}
  {{- end }}
  {{- if .Values.database.username }}
  DB_USERNAME: {{ .Values.database.username | b64enc }}
  {{- end }}
  {{- if .Values.database.password }}
  DB_PASSWORD: {{ .Values.database.password | b64enc }}
  {{- end }}
  {{- if .Values.database.sslMode }}
  DB_SSL_MODE: {{ .Values.database.sslMode | b64enc }}
  {{- end }}
  {{- end }}
  
  # Redis 连接信息
  {{- if .Values.redis.enabled }}
  {{- if .Values.redis.host }}
  REDIS_HOST: {{ .Values.redis.host | b64enc }}
  {{- end }}
  {{- if .Values.redis.port }}
  REDIS_PORT: {{ .Values.redis.port | toString | b64enc }}
  {{- end }}
  {{- if .Values.redis.password }}
  REDIS_PASSWORD: {{ .Values.redis.password | b64enc }}
  {{- end }}
  {{- if .Values.redis.database }}
  REDIS_DB: {{ .Values.redis.database | toString | b64enc }}
  {{- end }}
  {{- end }}
  
  # JWT 密钥
  {{- if .Values.auth.jwt.secret }}
  JWT_SECRET: {{ .Values.auth.jwt.secret | b64enc }}
  {{- end }}
  
  # API 密钥
  {{- if .Values.auth.apiKey }}
  API_KEY: {{ .Values.auth.apiKey | b64enc }}
  {{- end }}
  
  # 外部服务认证信息
  {{- if .Values.external.services }}
  {{- range $name, $service := .Values.external.services }}
  {{- if $service.apiKey }}
  {{ upper $name }}_API_KEY: {{ $service.apiKey | b64enc }}
  {{- end }}
  {{- if $service.secret }}
  {{ upper $name }}_SECRET: {{ $service.secret | b64enc }}
  {{- end }}
  {{- if $service.token }}
  {{ upper $name }}_TOKEN: {{ $service.token | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  
  # 监控系统认证信息
  {{- if .Values.monitoring.prometheus.basicAuth }}
  PROMETHEUS_USERNAME: {{ .Values.monitoring.prometheus.basicAuth.username | b64enc }}
  PROMETHEUS_PASSWORD: {{ .Values.monitoring.prometheus.basicAuth.password | b64enc }}
  {{- end }}
  
  {{- if .Values.monitoring.grafana.adminPassword }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.monitoring.grafana.adminPassword | b64enc }}
  {{- end }}
  
  # 追踪系统认证信息
  {{- if .Values.tracing.jaeger.auth }}
  JAEGER_USERNAME: {{ .Values.tracing.jaeger.auth.username | b64enc }}
  JAEGER_PASSWORD: {{ .Values.tracing.jaeger.auth.password | b64enc }}
  {{- end }}

---
{{/*
Nova Proxy TLS Secret 模板
用于存储 TLS 证书
*/}}
{{- if and .Values.tls.enabled .Values.tls.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nova-proxy.fullname" . }}-tls
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nova-proxy.labels" . | nindent 4 }}
    component: tls
    {{- with .Values.extra.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.tls.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.cert | b64enc }}
  tls.key: {{ .Values.tls.key | b64enc }}
  {{- if .Values.tls.ca }}
  ca.crt: {{ .Values.tls.ca | b64enc }}
  {{- end }}
{{- end }}

---
{{/*
Nova Proxy Registry Secret 模板
用于拉取私有镜像
*/}}
{{- if .Values.image.createPullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nova-proxy.fullname" . }}-registry
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nova-proxy.labels" . | nindent 4 }}
    component: registry
    {{- with .Values.extra.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.image.pullSecretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.image.registry .Values.image.pullSecret.username .Values.image.pullSecret.password (printf "%s:%s" .Values.image.pullSecret.username .Values.image.pullSecret.password | b64enc) | b64enc }}
{{- end }}

---
{{/*
Nova Proxy Database Secret 模板
用于存储数据库连接信息
*/}}
{{- if and .Values.database.enabled .Values.database.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nova-proxy.fullname" . }}-database
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nova-proxy.labels" . | nindent 4 }}
    component: database
    {{- with .Values.extra.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.database.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  host: {{ .Values.database.host | b64enc }}
  port: {{ .Values.database.port | toString | b64enc }}
  name: {{ .Values.database.name | b64enc }}
  username: {{ .Values.database.username | b64enc }}
  password: {{ .Values.database.password | b64enc }}
  ssl-mode: {{ .Values.database.sslMode | default "require" | b64enc }}
  url: {{ printf "postgresql://%s:%s@%s:%v/%s?sslmode=%s" .Values.database.username .Values.database.password .Values.database.host .Values.database.port .Values.database.name (.Values.database.sslMode | default "require") | b64enc }}
{{- end }}

---
{{/*
Nova Proxy Redis Secret 模板
用于存储 Redis 连接信息
*/}}
{{- if and .Values.redis.enabled .Values.redis.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nova-proxy.fullname" . }}-redis
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "nova-proxy.labels" . | nindent 4 }}
    component: redis
    {{- with .Values.extra.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.redis.secretAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.extra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  host: {{ .Values.redis.host | b64enc }}
  port: {{ .Values.redis.port | toString | b64enc }}
  password: {{ .Values.redis.password | b64enc }}
  database: {{ .Values.redis.database | toString | b64enc }}
  url: {{ printf "redis://:%s@%s:%v/%v" .Values.redis.password .Values.redis.host .Values.redis.port .Values.redis.database | b64enc }}
{{- end }}